AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tide-maker

  SAM Template for tide-maker

Globals:
  Function:
    Timeout: 600
    MemorySize: 256

Resources:

  H5Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: h5-lib-layer
      ContentUri: 'dependencies/'
      RetentionPolicy: Retain
      CompatibleRuntimes:
        - python3.7

  mapgetretriever:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: map_get_retriever.lambda_handler
      Runtime: python3.8
      CodeUri: functions/map_get_retriever/
      Role: 'arn:aws:iam::659933455233:role/testing_role'
      Environment:
        Variables:
          DATA_SRC: !GetAtt Table3.TableName
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /map
            Method: GET

  h5query:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: h5_quary.lambda_handler
      Runtime: python3.7
      Role: 'arn:aws:iam::659933455233:role/testing_role'
      CodeUri: functions/h5_query/
      Description: ''
      Environment:
        Variables:
          TIME_TABLE: !GetAtt Table4.TableName
          DATA_BUCKET: !GetAtt Bucket1.BucketName

  h5extract:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: h5_extract.lambda_handler
      Runtime: python3.7
      Role: 'arn:aws:iam::659933455233:role/testing_role'
      CodeUri: functions/h5_extract/
      Description: ''
      Layers: 
        - !Ref H5Layer
      Environment:
        Variables:
          DATA_DEST: !GetAtt Table1.TableName
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'

  streamlinesprocessor:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: s111_to_streamlines.lambda_handler
      Runtime: python3.7
      Role: 'arn:aws:iam::659933455233:role/testing_role'
      CodeUri: functions/s111_to_streamlines/
      Description: ''
      Environment:
        Variables:
          DATA_DEST: !GetAtt Table2.TableName
      Layers: 
        - !Ref H5Layer
      Events:
        DynamoDB1:
          Type: DynamoDB
          Properties:
            Stream:
              !GetAtt Table1.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1

  Table1:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: group_name
          AttributeType: S
      KeySchema:
        - AttributeName: group_name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  Table2:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: group_name
          AttributeType: S
      KeySchema:
        - AttributeName: group_name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  Table3:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: source_name
          AttributeType: S
      KeySchema:
        - AttributeName: source_name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  Table4:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: dataset
          AttributeType: S
      KeySchema:
        - AttributeName: dataset
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  Bucket1:
    Type: 'AWS::S3::Bucket'
