name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r functions/requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 functions/*.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 functions/*.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Lint YAML with cfn-lint
      run: |
        pip install cfn-lint
        cfn-lint --template template.yaml --region us-east-1 --ignore-checks W
        